/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuestsRouteImport } from './routes/quests'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnitUnitIdNodeIdRouteImport } from './routes/unit.$unitId.$nodeId'
import { Route as LessonUnitIdNodeIdLessonIdRouteImport } from './routes/lesson.$unitId.$nodeId.$lessonId'

const QuestsRoute = QuestsRouteImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitUnitIdNodeIdRoute = UnitUnitIdNodeIdRouteImport.update({
  id: '/unit/$unitId/$nodeId',
  path: '/unit/$unitId/$nodeId',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonUnitIdNodeIdLessonIdRoute =
  LessonUnitIdNodeIdLessonIdRouteImport.update({
    id: '/lesson/$unitId/$nodeId/$lessonId',
    path: '/lesson/$unitId/$nodeId/$lessonId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/profile': typeof ProfileRoute
  '/quests': typeof QuestsRoute
  '/unit/$unitId/$nodeId': typeof UnitUnitIdNodeIdRoute
  '/lesson/$unitId/$nodeId/$lessonId': typeof LessonUnitIdNodeIdLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/profile': typeof ProfileRoute
  '/quests': typeof QuestsRoute
  '/unit/$unitId/$nodeId': typeof UnitUnitIdNodeIdRoute
  '/lesson/$unitId/$nodeId/$lessonId': typeof LessonUnitIdNodeIdLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/profile': typeof ProfileRoute
  '/quests': typeof QuestsRoute
  '/unit/$unitId/$nodeId': typeof UnitUnitIdNodeIdRoute
  '/lesson/$unitId/$nodeId/$lessonId': typeof LessonUnitIdNodeIdLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/leaderboard'
    | '/profile'
    | '/quests'
    | '/unit/$unitId/$nodeId'
    | '/lesson/$unitId/$nodeId/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/leaderboard'
    | '/profile'
    | '/quests'
    | '/unit/$unitId/$nodeId'
    | '/lesson/$unitId/$nodeId/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/leaderboard'
    | '/profile'
    | '/quests'
    | '/unit/$unitId/$nodeId'
    | '/lesson/$unitId/$nodeId/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeaderboardRoute: typeof LeaderboardRoute
  ProfileRoute: typeof ProfileRoute
  QuestsRoute: typeof QuestsRoute
  UnitUnitIdNodeIdRoute: typeof UnitUnitIdNodeIdRoute
  LessonUnitIdNodeIdLessonIdRoute: typeof LessonUnitIdNodeIdLessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quests': {
      id: '/quests'
      path: '/quests'
      fullPath: '/quests'
      preLoaderRoute: typeof QuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unit/$unitId/$nodeId': {
      id: '/unit/$unitId/$nodeId'
      path: '/unit/$unitId/$nodeId'
      fullPath: '/unit/$unitId/$nodeId'
      preLoaderRoute: typeof UnitUnitIdNodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$unitId/$nodeId/$lessonId': {
      id: '/lesson/$unitId/$nodeId/$lessonId'
      path: '/lesson/$unitId/$nodeId/$lessonId'
      fullPath: '/lesson/$unitId/$nodeId/$lessonId'
      preLoaderRoute: typeof LessonUnitIdNodeIdLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeaderboardRoute: LeaderboardRoute,
  ProfileRoute: ProfileRoute,
  QuestsRoute: QuestsRoute,
  UnitUnitIdNodeIdRoute: UnitUnitIdNodeIdRoute,
  LessonUnitIdNodeIdLessonIdRoute: LessonUnitIdNodeIdLessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
